# Generated by Django 3.0.1 on 2020-01-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('img', models.ImageField(upload_to='images\\')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
