# Generated by Django 3.0.1 on 2020-01-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlist',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
